sudo: false
language: ruby
rvm:
  - 2.3.4
before_install: gem install bundler -v 1.15.4

services:
  - mongodb

addons:
  apt:
    sources:
      - mongodb-3.4-precise
    packages:
      - mongodb-org-server
